name: Python Code Style Check

on: push

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    
    - name: Install dependencies
      run: |
        pip install black flake8
      # Cache dependencies for faster workflow runs
      # See https://github.com/actions/cache for more info
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Run black
      run: black --check --line-length=100 .
      
    - name: Run flake8
      run: flake8 --check --line-length=100 .
